### ISSUE TITLE
Can't use with Laravel Mix

### ISSUE THREAD

**Issue by nivv** [Douglasdc3/laravel-mix-svg#3]
When trying to use this plugin I get this error:

```
/Users/username/projects/project/webpack.mix.project.js:31
mix.svg({
    ^

TypeError: mix.svg is not a function
```

Do I need to register the plugin somewhere perhaps?

**Comment by Douglasdc3** [comment]
@nivv make sure you add `require('laravel-mix-svg');` in your mix file.

**Comment by nivv** [comment]
@Douglasdc3 thanks! Totally forgot about that!
