### ISSUE TITLE
Add ability to recursively import SVGs

### ISSUE THREAD

**Issue by kylemilloy** [Douglasdc3/laravel-mix-svg#8]
Currently the lib ignores sub-directories within the resources/svg (or whichever) folder. A recursive search over sub-dirs would be great. See #7 for details how this is incorporated.

**Comment by Douglasdc3** [comment]
Merged and tagged as v0.4.0 thanks for including this feature!

**Comment by jalendport** [comment]
This doesn't seem to be totally working; for instance, here's my folder structure:

```
web/assets/icons
  16/
    category-1/
      my-icon.svg
    category-2/
      my-other-icon.svg
  48/
    category-1/
      my-icon.svg
    category-2/
      my-other-icon.svg
```

When I run Mix I'm getting the following error: `Error: ENOENT: no such file or directory, open './web/assets/icons/category-1/my-icon.svg'` (missing the icon size folder (`16` / `48`). It seems like maybe the PR doesn't account for more than one level of subdirectories?

**Comment by kylemilloy** [comment]
Show me your webpack code?

**Comment by jalendport** [comment]
Sure thing:


```
let mix = require("laravel-mix");

let config = {
  paths: {
    src: {
      js: "./src/js/",
    },
  },
  globs: {
    svg: [
      "./web/assets/icons/",
      "./web/assets/logos/",
    ],
  },
};

require('laravel-mix-svg');

mix.svg({
  class: '',
  assets: config.globs.svg,
  output: config.paths.src.js + 'svg.js',
});
```

I did strip out the unrelated stuff, but if you want everything let me know and I can give you the whole kit-and-kaboodle 😜

**Comment by kylemilloy** [comment]
Fixed in #9

**Comment by kylemilloy** [comment]
Changed walker to: 

```js
walker(dir, filelist = [], prefix = "") {
    let files = fs.readdirSync(dir);

    files.forEach(file => {
        if (fs.statSync(dir + file).isDirectory()) {
            let folder = file + "/";

            filelist = this.walker(dir + folder, filelist, prefix + folder);
        } else {
            if (!file.endsWith("svg")) return;

            filelist.push(prefix + file);
        }
    });

    return filelist;
}
```

prefix wasn't compounding as it walked across folders...added `this.walker(dir + folder, filelist, prefix + folder);` to ~Line 79 which takes the past prefix into account when actioning itself recursively.

**Comment by Douglasdc3** [comment]
Tagged a  new release with the latest patches.

**Comment by jalendport** [comment]
@kylemilloy thanks for the quick fix! Figured it was something like that, but not familiar enough with the `fs` module to try to fix it myself.

Thanks as well @Douglasdc3 for merging and tagging...
